# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import noobapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('noobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=noobapp.models.upload_location),
        ),
    ]
